# Site settings
title: ADD.re
tag_text: ADD.re
description: ADD.re is a website for looking up MAC vendor details.

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
