# Site settings
title: Add.re - MAC Address Lookup
tag_text: Add.re
description: ADD.re is a website for looking up MAC vendor details.

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
